Animal: Cat 
Thing: Mat

The [%Animal] sat on the [%Thing].
# Hello World
{{TOC}}
This is iA Writer
- [ ] Task One
- [ ] Task Two
And to whit, [^This is a footnote]

## Heading Number 2
### Heading Number 3
### Alternative
![My Link](IA_Writer_Logo.png)
![This is an image](http://example.com/image.jpg)
[Another link](http://google.com/)